#%RAML 1.0 NamedExample
[
  {
    "airline": "AirIndia",
    "seats": "40",
    "destination": "Hyderabad"
  },
  {
    "airline": "Indigo",
    "seats": "40",
    "destination": "Bangalore"
  },
  {
    "airline": "Airbus",
    "seats": "50",
    "destination": "Hyderabad"
  }
]