#%RAML 1.0
title: AirLines_CaseStudy


version: v1
protocols:
  - HTTPS
  - HTTP

/routes:
  post:
    queryParameters:
      destination: string
    body:
      application/json:
        type: !include file/routedataType.raml
    responses:
      201:
        body:
          application/json:
            examples: 
              ex1 : !include file/response1example.raml
              ex2: !include file/routeexample.raml
    
